In [1]:
#1.Debug the given code
#import pandas as pd

#data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
       # 'Feature2': [5.5, 6.7, 8.9]}

#df = pd.DataFrame(data)
#df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

#print(df)

import pandas as pd

data = {'Feature1': ['10', '20', '30'], # Corrected 'Thirty' to '30'
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)

print(df)

   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [2]:
#2.
#import pandas as pd

#data = {'A': [1, 2, None],  # Missing value
 #       'B': [4, None, 6]}  # Missing value

#df = pd.DataFrame(data)
#mean_value = df.mean()
#df.fillna(mean_value)  # Error: fillna() does not modify in place

#print(df)
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()

df.fillna(mean_value, inplace=True)   #  modifies df directly

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [3]:
#3.from sklearn.linear_model import LinearRegression
#import numpy as np

#X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
#y = np.array([2, 4, 6, 8, 10])

#model = LinearRegression()
#model.fit(X, y)

from sklearn.linear_model import LinearRegression
import numpy as np

# Reshape X to make it 2D
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print("Coefficient:", model.coef_)
print("Intercept:", model.intercept_)


Coefficient: [2.]
Intercept: 0.0


In [4]:
#4.
#from sklearn.preprocessing import StandardScaler
#import numpy as np

#data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

#scaler = StandardScaler()
#scaled_data = scaler.fit_transform(data)

#print(scaled_data)

from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1, 1)  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [5]:
#5.
#from sklearn.linear_model import LogisticRegression

#X = [[1, 2], [3, 4], [5, 6]]
#y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

#model = LogisticRegression()
#model.fit(X, y)
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']

#  Convert 'yes'/'no' to 1/0
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

model = LogisticRegression()
model.fit(X, y_encoded)

print("Classes:", encoder.classes_)   # ['no' 'yes']
print("Predictions:", model.predict(X))


Classes: ['no' 'yes']
Predictions: [1 1 1]


In [6]:
#6.import pandas as pd
#from sklearn.preprocessing import OneHotEncoder

#df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

#encoder = OneHotEncoder()
#encoded = encoder.fit_transform(df['Category'])   # Error: Data should be reshaped
#print(encoded)

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])   # FIXED

print(encoded.toarray())      # toarray() to see 0/1 encoding
print(encoder.categories_)    # see which categories were encoded


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[array(['A', 'B', 'C'], dtype=object)]


In [7]:
#6.
#from sklearn.model_selection import train_test_split

#X = [[1, 2], [3, 4], [5, 6], [7, 8]]
#y = [0, 1, 0]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  #  Now y has 4 labels for 4 samples

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train: [[7, 8], [1, 2], [5, 6]]
X_test: [[3, 4]]
y_train: [1, 0, 0]
y_test: [1]


In [8]:
#7.from sklearn.linear_model import LogisticRegression

#X_train = [[1, 2], [3, 4], [5, 6]]
#y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

#model = LogisticRegression()
#model.fit(X_train, y_train)

from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

#  Step 1: Encode labels
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)  # "no"→0, "yes"→1

#  Step 2: Fit model
model = LogisticRegression()
model.fit(X_train, y_train_encoded)

print("Encoded classes:", encoder.classes_)        # ['no' 'yes']
print("Model predictions (encoded):", model.predict(X_train))
print("Predictions (original labels):", encoder.inverse_transform(model.predict(X_train)))


Encoded classes: ['no' 'yes']
Model predictions (encoded): [1 1 1]
Predictions (original labels): ['yes' 'yes' 'yes']


In [9]:
#8.
#import numpy as np
#import pandas as pd
#from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
#X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
#y_train = np.array([10, 20, 30])

#model = LinearRegression()
#model.fit(X_train, y_train)  

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train_raw = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train_raw = np.array([10, 20, 30])

# Combine X and y into a DataFrame to easily drop rows
df = pd.DataFrame(X_train_raw)
df['target'] = y_train_raw

# Drop rows with any NaN values
df_cleaned = df.dropna()

X_train_cleaned = df_cleaned.drop('target', axis=1).values
y_train_cleaned = df_cleaned['target'].values

if X_train_cleaned.shape[0] > 0: # Check if there's data left after dropping NaNs
    model = LinearRegression()
    model.fit(X_train_cleaned, y_train_cleaned)
    print("X_train after dropping NaNs:\n", X_train_cleaned)
    print("y_train after dropping NaNs:\n", y_train_cleaned)
    print("Model coefficients:", model.coef_)
    print("Model intercept:", model.intercept_)
else:
    print("No data remaining after dropping rows with missing values.")


X_train after dropping NaNs:
 [[1. 2.]
 [5. 6.]]
y_train after dropping NaNs:
 [10 30]
Model coefficients: [2.5 2.5]
Model intercept: 2.500000000000007


In [10]:
#9.
#from sklearn.tree import DecisionTreeClassifier

#X_train = [[1, 2], [3, 4], [5, 6]]
#y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

#model = DecisionTreeClassifier()
#model.fit(X_train, y_train)

from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]   #  String labels are fine

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print("Classes:", model.classes_)
print("Prediction for [4,5]:", model.predict([[4, 5]]))


Classes: ['ham' 'spam']
Prediction for [4,5]: ['ham']


In [11]:
#10.
#from sklearn.svm import SVC

#X_train = [[1, 100], [2, 200], [3, 300]]
#y_train = [0, 1, 0]

#model = SVC()
#model.fit(X_train, y_train)
#print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Training data
X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

# 1. Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

#  2. Train the model on scaled data
model = SVC()
model.fit(X_train_scaled, y_train)

# 3. Scale the test data before predicting
test_point = scaler.transform([[1, 150]])
print("Prediction:", model.predict(test_point))


Prediction: [0]
